[package]
name = "psf"
version = "0.1.0"
edition = "2021"

[dependencies]
qfall-crypto = { git = "https://github.com/qfall/crypto", branch = "perturbation_sampling" }
qfall-math = { git = "https://github.com/qfall/math", branch = "cholesky_decomp_f64_precision" }
serde_json = "1.0"